version: 0.2

proxy:
    upload-artifacts: yes
    logs: yes
            
phases:
  install:
    runtime-versions:
      java: openjdk8
    commands:
      - echo install
  pre_build:
    commands:
      - echo pre_build
  build:
    commands:
      - mvn package
      - echo build
  post_build:
    commands:
      - echo post_build
reports:
  report-name-or-arn:
    files:
      - location
      - location
    base-directory: location
    discard-paths: yes
    file-format: JunitXml | CucumberJson
artifacts:
  files:
    - target\rest-api-h2-aws-codepipeline-0.0.1-SNAPSHOT.jar